services:
  - type: web
    name: exoplanet-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
